version: '3.8'

services:
  crypto-detector:
    build: .
    container_name: crypto-signal-detector
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./charts:/app/charts
      - ./logs:/app/logs
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
